### ISSUE TITLE
Other errors encountered after user clears data

### ISSUE THREAD

**Issue by dhleong** [adorsys/secure-storage-android#44]
See #42 for the original issue, but the repro, at least, is the same for this issue.

The first time running the app after clearing data and restarting, I get this:

```
    io.reactivex.exceptions.OnErrorNotImplementedException: Failed to load generated key pair from keystore
    Caused by: de.adorsys.android.securestoragelibrary.SecureStorageException: Failed to load generated key pair from keystore
        at de.adorsys.android.securestoragelibrary.a.b(Unknown Source:97)
        at de.adorsys.android.securestoragelibrary.a.c(Unknown Source:6)
        at de.adorsys.android.securestoragelibrary.SecurePreferences.setValue(Unknown Source:10)
        at co.myapp.modules.SecurePrefsEditor.putString(PrefsModule.kt:115)
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:68)
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:41)
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.security.ProviderException: Failed to load generated key pair from keystore
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:530)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:472)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
        at de.adorsys.android.securestoragelibrary.a.b(Unknown Source:84)
        at de.adorsys.android.securestoragelibrary.a.c(Unknown Source:6) 
        at de.adorsys.android.securestoragelibrary.SecurePreferences.setValue(Unknown Source:10) 
        at co.myapp.modules.SecurePrefsEditor.putString(PrefsModule.kt:115) 
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:68) 
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:41) 
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36) 
        at io.reactivex.Completable.subscribe(Completable.java:2309) 
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.security.UnrecoverableKeyException: Failed to obtain information about key
        at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:242)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:308)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:521)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:472) 
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727) 
        at de.adorsys.android.securestoragelibrary.a.b(Unknown Source:84) 
        at de.adorsys.android.securestoragelibrary.a.c(Unknown Source:6) 
        at de.adorsys.android.securestoragelibrary.SecurePreferences.setValue(Unknown Source:10) 
        at co.myapp.modules.SecurePrefsEditor.putString(PrefsModule.kt:115) 
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:68) 
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:41) 
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36) 
        at io.reactivex.Completable.subscribe(Completable.java:2309) 
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: android.security.KeyStoreException: Key not found
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1273)
        at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:244)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:308) 
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:521) 
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:472) 
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727) 
        at de.adorsys.android.securestoragelibrary.a.b(Unknown Source:84) 
        at de.adorsys.android.securestoragelibrary.a.c(Unknown Source:6) 
        at de.adorsys.android.securestoragelibrary.SecurePreferences.setValue(Unknown Source:10) 
        at co.myapp.modules.SecurePrefsEditor.putString(PrefsModule.kt:115) 
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:68) 
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:41) 
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36) 
        at io.reactivex.Completable.subscribe(Completable.java:2309) 
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

After that, I get a slightly different error:

```
    io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
    Caused by: de.adorsys.android.securestoragelibrary.SecureStorageException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
        at de.adorsys.android.securestoragelibrary.a.b(Unknown Source:67)
        at de.adorsys.android.securestoragelibrary.SecurePreferences.setValue(Unknown Source:13)
        at co.myapp.modules.SecurePrefsEditor.putString(PrefsModule.kt:115)
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:68)
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:41)
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: de.adorsys.android.securestoragelibrary.SecureStorageException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
        at de.adorsys.android.securestoragelibrary.a.e(Unknown Source:66)
        at de.adorsys.android.securestoragelibrary.a.b(Unknown Source:19)
        at de.adorsys.android.securestoragelibrary.SecurePreferences.setValue(Unknown Source:13) 
        at co.myapp.modules.SecurePrefsEditor.putString(PrefsModule.kt:115) 
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:68) 
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:41) 
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36) 
        at io.reactivex.Completable.subscribe(Completable.java:2309) 
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
        at de.adorsys.android.securestoragelibrary.a.e(Unknown Source:38)
        at de.adorsys.android.securestoragelibrary.a.b(Unknown Source:19) 
        at de.adorsys.android.securestoragelibrary.SecurePreferences.setValue(Unknown Source:13) 
        at co.myapp.modules.SecurePrefsEditor.putString(PrefsModule.kt:115) 
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:68) 
        at co.myapp.modules.AuthModule$authUpdater$1$1.call(AuthModule.kt:41) 
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36) 
        at io.reactivex.Completable.subscribe(Completable.java:2309) 
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

Thanks!

**Comment by dhleong** [comment]
Okay I looked into this further because I encountered this crash signing out normally just now. It looks like the key (via `keyStore.getKey(ALIAS, null)`) exists, but the cert (via `keyStore.getCertificate(ALIAS)`, on P+) does *not*. Perhaps on `P+` we should check this, as well?

**Comment by luckyhandler** [comment]
Hey, I already pushed something in this direction. Check out https://github.com/adorsys/secure-storage-android/commit/a42e59287d37561859df35184a6db3333cb7465f. Good point though to only do that for `P+`. Didn't comment until now as I couldn't test it until now

**Comment by dhleong** [comment]
@luckyhandler Thanks for the quick feedback. I'll see if I can build this locally and test it. I suspect it may also be important to catch `ProviderException` and check if its cause is `UnrecoverableKeyException` or `KeyStoreException` as seen in the stacktrace above.

**Comment by dhleong** [comment]
@luckyhandler Installing and testing locally was easy; that commit definitely helps, but I can still consistently reproduce the first crash on my device, the commit just helps recover on a second run. Looking to see if I can find anything helpful right now.

**Comment by dhleong** [comment]
Okay, it looks like that first exception is caused by me editing the the shared preferences on two separate threads. If I marshall my edits to a single thread the exception goes away. I don't think the library responsible for that, but it might be worth noting in the readme that the APIs are not threadsafe (I see you mention using a background thread at one point). Feel free to close this when you deploy that commit 👍

**Comment by luckyhandler** [comment]
Cool, thanks for your help in solving this issue and for sharing the insight. Happy I could help and I will deploy version 1.1.1 as soon as possible.

**Comment by dhleong** [comment]
No problem! Thanks for being so fast with updates :)

**Comment by luckyhandler** [comment]
just updated the `keyPairExists` method so that it should work for all api levels. If you want check it out --> https://github.com/adorsys/secure-storage-android/commit/90ec095ac4f3dadaec5356aa97a2f8da16ffbc86

**Comment by luckyhandler** [comment]
Bugfix-PR currently in Review https://github.com/adorsys/secure-storage-android/pull/45
