### ISSUE TITLE
NPE on KeyStore.getCertificate on null object, version 1.1.1 also in 1.2.2

### ISSUE THREAD

**Issue by MxitarHakobyan** [adorsys/secure-storage-android#67]
KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1964)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:149)
        at java.security.KeyStore.getCertificate(KeyStore.java:1120)
        at de.adorsys.android.securestoragelibrary.a.b(Unknown Source:15)
        at de.adorsys.android.securestoragelibrary.a.c(Unknown Source:0)
        at de.adorsys.android.securestoragelibrary.SecurePreferences.setValue(Unknown Source:10)
        at am.gear.app.auth.SecureAuthentication.lambda$setRegistrationId$6$SecureAuthentication(SecureAuthentication.java:93)
        at am.gear.app.auth.-$$Lambda$SecureAuthentication$_oxAIWscGFbBpg741CJvvfhQbNM.run(Unknown Source:4)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:107)
        at io.reactivex.internal.disposables.EmptyDisposable.complete(EmptyDisposable.java:68)
        at io.reactivex.internal.operators.completable.CompletableEmpty.subscribeActual(CompletableEmpty.java:27)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by drilonrecica** [comment]
Should be fixed. See #62
