### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long

### ISSUE THREAD

**Issue by vadim-duran** [adorsys/secure-storage-android#87]
Hello. adorsys
Version lib - 1.1.0
This error appear:
Samsung: Galaxy J7,J2
Prestigio: PMT3171_3G

**Comment by drilonrecica** [comment]
Hi @vadim-duran ,
Sorry for the late reply.
Could you please send us a full stack trace because the line you posted doesnt help us much.
Thanks

**Comment by drilonrecica** [comment]
@IsabellaCaspari Please close this issue due to no recent activity

**Comment by kmno** [comment]
Caused by java.lang.RuntimeException: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long
       at com.android.org.conscrypt.NativeCrypto.ENGINE_load_private_key(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLEngine.getPrivateKeyById(OpenSSLEngine.java:66)
       at android.security.AndroidKeyStore.engineGetKey(AndroidKeyStore.java:86)
       at java.security.KeyStore.getKey(KeyStore.java:253)
       at o.Іɍ.ˎ(:133)
       at o.гӏ.ˊ(:55)
       at o.ɼǃ.onCreate(:5107)
       at android.app.Activity.performCreate(Activity.java:6289)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
